<?php
/**
 @Frame Work Name     StartPHP
 @Copyright    Cat Catalpa Vitality (Shanghai) Infomation & Technology Co., Ltd
 @Official SIte     https://startphp.catcatalpa.com
 @This website is generated by the SartPHP Framework,commercial use is prohibited without the permission of the copyright owner
 */
//StartPHP入口文件
//核心配置常量
//echo("111");
define('DIR',__DIR__);//项目根目录
define('CORE',DIR.'/core/');//core目录
define('CONFIG',DIR.'/config/');//config目录
//加载核心库
//如需增加其他配置文件，请在core/bolt.php的spl_autoload_register()方法中手动引用
require_once(CORE."bolt.php");
//初始化
$bolt = new bolt();
$init = $bolt -> init();